version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: web-diem-backend
    expose:
      - "8000"
    env_file:
      - ./backend/.env
    environment:
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8000
    volumes:
      - ./backend/students.db:/app/students.db
      - ./backend/static:/app/static
      - ~/access.log:/app/logs/access.log
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web-diem-frontend
    expose:
      - "3000"
    environment:
      - API_URL=http://backend:8000
      - DOCKER_ENV=true
    depends_on:
      - backend
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    command: tunnel run --token ${CF_TOKEN}
    depends_on:
      - frontend
      - backend
